create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title VARCHAR(80) NOT NULL,
    site_url TEXT NOT NULL,
    site_description TEXT,
    rating SMALLINT DEFAULT 1
);